#!/bin/bash

alias sb="source ~/bashprofile"
alias eb="gedit ~/bashprofile"
alias ros2s="source ~/.ros2rc"

export PM_PACKAGES_ROOT=$HOME/packman-repo

# Isaac Sim root directory
export ISAACSIM_PATH="${HOME}/.local/share/ov/pkg/isaac_sim-2022.2.1"
# Isaac Sim python executable
alias ISAACSIM_PYTHON="${ISAACSIM_PATH}/python.sh"
# Isaac Sim app
alias ISAACSIM="${ISAACSIM_PATH}/isaac-sim.sh"

#autojump
source /usr/share/autojump/autojump.bash

xhost +

